version: '3'

services:
  backend:
    build: backend
    container_name: backend
    env_file:
      - backend/.env
    ports:
      - 8000:8000
    volumes:
      - db-data:/app/backend

  frontend:
    build: frontend
    container_name: frontend
    ports:
      - 3000:80

volumes:
  db-data: