# Generated by Django 4.2.5 on 2023-09-23 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='symbol',
            new_name='code',
        ),
    ]
