# Generated by Django 4.2.5 on 2023-10-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
