# Generated by Django 4.2.5 on 2023-10-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_quotes', '0003_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='tunnel_lower_limit',
            new_name='max_loss_percentage',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='tunnel_upper_limit',
            new_name='min_profit_percentage',
        ),
    ]
