# Generated by Django 4.2.5 on 2023-10-05 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_quotes', '0005_asset_purchase_price_alter_asset_max_loss_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='max_loss_percentage',
            new_name='drop_percentage',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='min_profit_percentage',
            new_name='increase_percentage',
        ),
    ]
